In [3]:
import numpy as np 
import pandas as pd 
from sklearn import preprocessing
from sklearn.svm import SVC
from sklearn.model_selection import KFold
from sklearn.metrics import confusion_matrix
from sklearn.neural_network import MLPClassifier

def segment_signal (data, window_size):
	N = data.shape[0]
	dim = data.shape[1]
	K = N/window_size
	segments = np.empty((K, window_size, dim))
	for i in range(K):
		segment = data[i*window_size:i*window_size+window_size,:]
		segments[i] = np.vstack(segment)
	return segments 
	
dataSet = pd.read_excel('/Users/SnehaPrabakar/Documents/Year 3/Semester 2/CG3002-Capstone/P1Data.xlsx', header=None, delim_whitespace=True)

readings = dataSet.iloc[:, 1:7]
target = dataSet.iloc[:, 0]
arrReadings = readings.as_matrix()
arrTarget = np.reshape(target.as_matrix(), -1)

norm_Data = preprocessing.normalize(arrReadings)

kFold = KFold(n_splits=10, shuffle=True)
fold_index = 0
kfold = KFold(n_splits=10, shuffle=True)
fold_index = 0
for train, test in kfold.split(norm_Data):
    print('Starting NN fold %i' %fold_index)
    mlpclf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(70,),random_state=1)
    mlpclf.fit(norm_Data[train], arrTarget[train])
    nn_predictions = mlpclf.predict(norm_Data[test])
    accuracyNN = mlpclf.score(norm_Data[test],arrTarget[test])
    cmNN = confusion_matrix(arrTarget[test],nn_predictions)
    with open('evaluation.txt', 'a') as f:
     f.write('For %i fold\n' %fold_index)
     f.write('The classification accuracy for NN is %f\n' %accuracyNN)
     f.write('And the confusion matrix is:\n')
     f.write(np.array2string(cmNN))
     f.write('\n\n')
    
    print('The classification accuracy for NN is %f' %accuracyNN)
    print('And the confusion matrix is:')
    print(cmNN)
    fold_index += 1

Starting NN fold 0
The classification accuracy for NN is 0.737367
And the confusion matrix is:
[[308   7   0   5   1   0   0   0   2   1   0]
 [ 12 284   1   9   0  17   3   5   3   1   0]
 [  0   1 247   7   2  27   2   6   2   0   0]
 [ 16   4   4  91 127   2   0   8   0   4   2]
 [ 14   0   0  38 217   0   0   2   3   5   2]
 [  0  29  20   2   2 269   5  12   9   1   1]
 [  0   0   1   1   0   3 252   0   2   0   0]
 [  5  14  21  12   2  13   2 172  68   6   1]
 [  2  24  16   6   7  31   1  64 130  16   5]
 [  0   3   3  10   7   1   0   2   3 180   8]
 [  0   2   1   1   4   1   0   2   2  17 141]]
Starting NN fold 1
The classification accuracy for NN is 0.737689
And the confusion matrix is:
[[322   6   0   6   1   0   0   0   1   0   0]
 [  5 330   4   6   4  19   0   4   1   1   0]
 [  0   3 259   5   2  27   1   3   0   1   0]
 [ 18   3   0  89 118   5   0  10   2   2   1]
 [  7   1   0  49 198   2   0   2  11   5   2]
 [  1  33  19   6   2 258   4  14   6   0   1]
 [  1   1 